/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nimgame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Action;
import com.mycompany.nimgame.PlayWithPerson;
import com.mycompany.nimgame.PlayWithBot;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public HomePage() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NimGame = new javax.swing.JLabel();
        btn_choivoinguoi = new javax.swing.JButton();
        btn_choivoimay = new javax.swing.JButton();
        btn_luatchoi = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        backgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        setMinimumSize(new java.awt.Dimension(1380, 745));
        setPreferredSize(new java.awt.Dimension(1366, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NimGame.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        NimGame.setText("NIM GAME");
        getContentPane().add(NimGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        btn_choivoinguoi.setBackground(java.awt.SystemColor.activeCaption);
        btn_choivoinguoi.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn_choivoinguoi.setText("Chơi với người");
        btn_choivoinguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choivoinguoiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_choivoinguoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 300, 80));

        btn_choivoimay.setBackground(java.awt.SystemColor.activeCaption);
        btn_choivoimay.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn_choivoimay.setText("Chơi với máy");
        btn_choivoimay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choivoimayActionPerformed(evt);
            }
        });
        getContentPane().add(btn_choivoimay, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 250, 300, 80));

        btn_luatchoi.setBackground(java.awt.SystemColor.activeCaption);
        btn_luatchoi.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn_luatchoi.setText("Luật chơi");
        btn_luatchoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luatchoiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_luatchoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 300, 80));

        btn_thoat.setBackground(java.awt.SystemColor.activeCaption);
        btn_thoat.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 450, 300, 80));

        backgound.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        backgound.setIcon(new javax.swing.ImageIcon("D:\\study_space\\tai_lieu\\CT239_NienLuanCoSoNganhKTPM\\NimGame\\src\\main\\java\\images\\Bio.png")); // NOI18N
        getContentPane().add(backgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_choivoinguoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choivoinguoiActionPerformed
        File f = new File("file.txt");
        if (f.exists()) {
            Object[] option = {"Có", "Ván mới"};
            int x = JOptionPane.showOptionDialog(null, "Bạn có muốn chơi tiếp ván trước không ?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, option[0]);
            if (x == JOptionPane.YES_OPTION) {
                PlayWithPerson pvp = new PlayWithPerson(null, null);
                pvp.setVisible(true);
                setVisible(false);
            } else {
                f.delete();
                EnterName2 ten2nguoi = new EnterName2();
                ten2nguoi.setVisible(true);
                setVisible(false);
            }
        } else {
            EnterName2 ten2nguoi = new EnterName2();
            ten2nguoi.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btn_choivoinguoiActionPerformed

    private void btn_choivoimayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choivoimayActionPerformed
        EnterName1 ten1nguoi = new EnterName1();
        ten1nguoi.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_choivoimayActionPerformed

    private void btn_luatchoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luatchoiActionPerformed
        String luatChoi = "Trò chơi truyền thống Nim được chơi với một số đồng xu được sắp xếp thành nhiều đống, cách sắp số lượng đồng xu và \n"
                + "đống tùy thuộc vào bạn. Có hai người chơi, khi đến lượt, người chơi có thể lấy một số lượng tùy ý đồng xu từ một đống \n"
                + "duy nhất. Họ phải lấy ít nhất 1 đồng xu và họ không được lấy các đồng xu từ đống khác. Người thắng là người lấy đồng xu \n"
                + "cuối cùng, nghĩa là không còn đồng xu nào sau nước đi của người đó. ";
        JOptionPane.showMessageDialog(null, luatChoi, "Luật chơi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_luatchoiActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed

        int optionWindowClosing = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thoát khỏi trò chơi không?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (optionWindowClosing == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NimGame;
    private javax.swing.JLabel backgound;
    private javax.swing.JButton btn_choivoimay;
    private javax.swing.JButton btn_choivoinguoi;
    private javax.swing.JButton btn_luatchoi;
    private javax.swing.JButton btn_thoat;
    // End of variables declaration//GEN-END:variables
}
