/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */




/**
 *
 * @author DELL
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_choivoinguoi = new javax.swing.JButton();
        btn_choivoimay = new javax.swing.JButton();
        btn_luatchoi = new javax.swing.JButton();
        btn_xemdiem = new javax.swing.JButton();
        btn_thoát = new javax.swing.JButton();
        NimGame = new javax.swing.JLabel();
        btn_dangnhap = new javax.swing.JButton();
        btn_dangky = new javax.swing.JButton();
        backgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_choivoinguoi.setText("Chơi với người");
        btn_choivoinguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choivoinguoiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_choivoinguoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 450, 80));

        btn_choivoimay.setText("Chơi với máy");
        btn_choivoimay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choivoimayActionPerformed(evt);
            }
        });
        jPanel1.add(btn_choivoimay, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 450, 80));

        btn_luatchoi.setText("Luật chơi");
        btn_luatchoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luatchoiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_luatchoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 450, 80));

        btn_xemdiem.setText("Xem điểm");
        btn_xemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemdiemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_xemdiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 450, 80));

        btn_thoát.setText("Thoát");
        btn_thoát.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoátActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thoát, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 450, 80));

        NimGame.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        NimGame.setText("NIM GAME");
        jPanel1.add(NimGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        btn_dangnhap.setText("Đăng nhập");
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 140, 40));

        btn_dangky.setText("Đăng ký");
        jPanel1.add(btn_dangky, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 40, 130, 40));

        backgound.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\OneDrive\\Desktop\\NimGame\\src\\main\\java\\images\\Bio.jpg")); // NOI18N
        jPanel1.add(backgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_choivoinguoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choivoinguoiActionPerformed
        
    }//GEN-LAST:event_btn_choivoinguoiActionPerformed

    private void btn_choivoimayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choivoimayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_choivoimayActionPerformed

    private void btn_luatchoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luatchoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_luatchoiActionPerformed

    private void btn_xemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemdiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xemdiemActionPerformed

    private void btn_thoátActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoátActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_thoátActionPerformed

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NimGame;
    private javax.swing.JLabel backgound;
    private javax.swing.JButton btn_choivoimay;
    private javax.swing.JButton btn_choivoinguoi;
    private javax.swing.JButton btn_dangky;
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JButton btn_luatchoi;
    private javax.swing.JButton btn_thoát;
    private javax.swing.JButton btn_xemdiem;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
